version: '3.8'
services:
  backend:
    build: ./
    container_name: spring_backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"